export const TRAVEL_REPOSITORY_PROVIDER = 'TRAVEL_REPOSITORY_PROVIDER';
export const TRAVEL_SERVICE_PROVIDER = 'TRAVEL_SERVICE_PROVIDER';
export const TRAVEL_SERVICE_CONTAINER = 'TRAVEL_SERVICE_CONTAINER';
